name: Deploy Backend to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci
        # (se ejecuta en la raíz de tu proyecto)

      # (Opcional) Si usas un build step:
      # - name: Build project
      #   run: npm run build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'viba'                         # tu App Service name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: '.'                             # ruta al root de tu backend
